### ISSUE TITLE
Bluetooth disconnects all the time

### ISSUE THREAD

**Issue by sl4m01** [tomquist/esphome-b2500#115]
**Expected behavior**

Bluetooth connection

**Actual behavior**

No bluetooth connection

**Device information**

- ESP Board: ESP32 nodemcu USB C

- B2500 Brand: Marstek

- B2500 Version: HMJ Version 2

Hello all,
i am struggeling to get an bluetooth connection. The esp32 trys to re-connect all the time. The B2500D is only ~3m away from the esp32. I got a connection once or twice and collected some data (webUI and mqtt). But then connection was lost again. 

With my smartphone i do get a good bluetooth connection at the same spot. During esp32 operation the smartphone bluetooth was disabled.

Can i do something?

DEBUG log

```
17:19:09
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (154646) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e
17:19:09
[W]
[b2500:023]
Disconnected!
17:19:09
[E]
[esp32_ble_client:238]
[0] [7C:E7:12:19:A6:CF] Got ESP_GATTC_OPEN_EVT while not in connecting state, status=133
17:19:09
[W]
[esp32_ble_client:243]
[0] [7C:E7:12:19:A6:CF] Connection failed, status=133
17:19:09
[I]
[esp32_ble_client:110]
[0] [7C:E7:12:19:A6:CF] 0x00 Attempting BLE connection
17:19:09
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (155235) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e
17:19:09
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (155325) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e
17:19:09
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (155433) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e
17:19:10
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (155534) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x3e
17:19:10
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (155540) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e
17:19:10
[W]
[b2500:023]
Disconnected!
17:19:10
[E]
[esp32_ble_client:238]
[0] [7C:E7:12:19:A6:CF] Got ESP_GATTC_OPEN_EVT while not in connecting state, status=133
17:19:10
[W]
[esp32_ble_client:243]
[0] [7C:E7:12:19:A6:CF] Connection failed, status=133
17:19:10
[I]
[esp32_ble_client:110]
[0] [7C:E7:12:19:A6:CF] 0x00 Attempting BLE connection
17:19:10
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (155928) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e
17:19:10
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (156033) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e
17:19:12
[I]
[b2500:015]
Connected successfully!
17:19:34
[I]
[esp32_ble_client:337]
[0] [7C:E7:12:19:A6:CF] Connected
17:19:34
[I]
[main:023]
Connected to BLE device 1 (B2500)
17:19:42
[W]
[component:239]
Component esp32_ble took a long time for an operation (123 ms).
17:19:42
[W]
[component:240]
Components should block for at most 30 ms.
17:19:46
[W]
[component:239]
Component esp32_ble took a long time for an operation (129 ms).
17:19:46
[W]
[component:240]
Components should block for at most 30 ms.
17:20:06
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (212025) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x8
17:20:06
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (212045) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x8
17:20:06
[W]
[b2500:023]
Disconnected!
17:20:06
[I]
[main:106]
Disconnected from BLE device 1 (B2500)
17:20:07
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;31mE (212775) BT_BTM: BTM_BleScan scan not ac
17:20:07
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (212780) BT_APPL: bta_dm_ble_scan stop scan failed, status
17:20:07
[I]
[esp32_ble_client:110]
[0] [7C:E7:12:19:A6:CF] 0x00 Attempting BLE connection
17:20:08
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (213499) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e
17:20:08
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (213604) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e
17:20:08
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (213694) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e
17:20:08
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (213798) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x3e
17:20:08
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (213804) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x3e
17:20:08
[W]
[b2500:023]
Disconnected!
17:20:08
[E]
[esp32_ble_client:238]
[0] [7C:E7:12:19:A6:CF] Got ESP_GATTC_OPEN_EVT while not in connecting state, status=133
17:20:08
[W]
[esp32_ble_client:243]
[0] [7C:E7:12:19:A6:CF] Connection failed, status=133
17:20:08
[I]
[esp32_ble_client:110]


```

**Comment by sl4m01** [comment]
Now it is connected for a longer time. However i am getting this warnings in the debug log:
`17:26:48
[I]
[esp-idf:000][1;31m[BTU_TASK][0;32m
[0;33mW (614244) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x8
17:27:19
[W]
[component:239]
Component web_server took a long time for an operation (124 ms).
17:27:19
[W]
[component:240]
Components should block for at most 30 ms.
17:27:20
[W]
[component:239]
Component web_server took a long time for an operation (125 ms).
17:27:20
[W]
[component:240]
Components should block for at most 30 ms.
17:27:20
[W]
[component:239]
Component web_server took a long time for an operation (226 ms).
17:27:20
[W]
[component:240]
Components should block for at most 30 ms.
17:27:20
[W]
[component:239]
Component web_server took a long time for an operation (71 ms).
17:27:20
[W]
[component:240]
Components should block for at most 30 ms.
17:27:20
[W]
[component:239]
Component web_server took a long time for an operation (129 ms).
17:27:20
[W]
[component:240]
Components should block for at most 30 ms.
17:27:20
[W]
[component:239]
Component web_server took a long time for an operation (59 ms).
17:27:20
[W]
[component:240]
Components should block for at most 30 ms.
17:27:20
[W]
[component:239]
Component web_server took a long time for an operation (112 ms).
17:27:20
[W]
[component:240]
Components should block for at most 30 ms.
17:27:20
[W]
[component:239]
Component web_server took a long time for an operation (77 ms).
17:27:20
[W]
[component:240]
Components should block for at most 30 ms.
17:27:21
[W]
[component:239]
Component web_server took a long time for an operation (389 ms).
17:27:21
[W]
[component:240]
Components should block for at most 30 ms.
17:27:24
[W]
[component:239]
Component esp32_ble took a long time for an operation (63 ms).
17:27:24
[W]
[component:240]
Components should block for at most 30 ms.
17:27:32
[W]
[component:239]
Component esp32_ble took a long time for an operation (71 ms).
17:27:32
[W]
[component:240]
Components should block for at most 30 ms.
17:27:34
[W]
[component:239]
Component esp32_ble took a long time for an operation (60 ms).
17:27:34
[W]
[component:240]
Components should block for at most 30 ms.
17:27:39
[W]
[component:239]
Component esp32_ble took a long time for an operation (72 ms).
17:27:39
[W]
[component:240]
Components should block for at most 30 ms.
17:27:50
[W]
[component:239]
Component esp32_ble took a long time for an operation (80 ms).
17:27:50
[W]
[component:240]
Components should block for at most 30 ms.
17:27:50
[W]
[component:239]
Component esp32_ble took a long time for an operation (66 ms).
17:27:50
[W]
[component:240]
Components should block for at most 30 ms.
17:27:55
[W]
[component:239]
Component esp32_ble took a long time for an operation (83 ms).
17:27:55
[W]
[component:240]
Components should block for at most 30 ms.
17:28:03
[W]
[component:239]
Component esp32_ble took a long time for an operation (96 ms).
17:28:03
[W]
[component:240]
Components should block for at most 30 ms.
17:28:08
[W]
[component:239]
Component esp32_ble took a long time for an operation (80 ms).
17:28:08
[W]
[component:240]
Components should block for at most 30 ms.
17:28:11
[W]
[component:239]
Component esp32_ble took a long time for an operation (64 ms).
17:28:11
[W]
[component:240]
Components should block for at most 30 ms.
17:28:21
[W]
[component:239]
Component esp32_ble took a long time for an operation (93 ms).
17:28:22
[W]
[component:240]
Components should block for at most 30 ms.
17:28:31
[W]
[component:239]
Component esp32_ble took a long time for an operation (92 ms).
17:28:31
[W]
[component:240]
Components should block for at most 30 ms.`

**Comment by sl4m01** [comment]
Today I rebootet the b2500 and now I am getting the same error messages as above again. Seems not to work stable:(

**Comment by tomquist** [comment]
Which ESP are you using and what does your config look like?

**Comment by Marc9485** [comment]
Bluetooth Verbindung reißt bei mir auch mehrmals am Tag ab. Nachts dann auch über Stunden hinweg keine Verbindung. ESP32 und B2500 werden nur durch ein Garagendach getrennt und sind keine 2m voneinander entfernt. 10W Netzteil hängt am ESP bin am überlegen noch nen Elko und Tantal-Kondensator anzulöten.

**Comment by Marc9485** [comment]
![image](https://github.com/user-attachments/assets/b7d413dd-d5b1-4586-aedc-23247c7e5fdb)

**Comment by sl4m01** [comment]
Wusste nicht, dass ich auch deutsch schreiben kann :)
Habe die esp32 von Amazon: https://amzn.eu/d/durD3DF
Das ist die config welche ich benutzte, generiert mit deiner UI:
```
esphome:
  name: "b2500"
  friendly_name: "B2500"
  on_boot:
    priority: -100
    then:
      - lambda: id(b2500_device_generation_1).publish_state("2");
      - lambda: id(b2500_device_name_1).publish_state("B2500");

esp32:
  board: "esp32dev"
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      COMPILER_OPTIMIZATION_SIZE: y

# Enable logging
logger:
  level: INFO
ota:
  - platform: esphome
    password: "my_ota_password"
external_components:
  - source:
      type: git
      url: https://github.com/tomquist/esphome-b2500
      ref: "main"
    refresh: 0s
    components: [b2500]

wifi:
  ssid: "xxx"
  password: "xxx"
  reboot_timeout: 0s
  fast_connect: True
  on_connect:
    - logger.log:
        level: INFO
        format: "Connected to WiFi. Starting BLE scan."
  on_disconnect:
    - logger.log:
        level: INFO
        format: "Disconnected from WiFi. Stopping BLE scan."
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome-b2500"
web_server:
  port: 80
  ota: false
  js_include: "./v2/www.js"
  js_url: ""
  version: 2
captive_portal:
mqtt:
  id: mqtt_client
  broker: "xxx"
  port: 1883
  username: "xxx"
  password: "xxx"
  discovery: False
  reboot_timeout: 0s
  topic_prefix: "b2500"
  log_topic: "b2500/debug"
  on_connect:
    - logger.log:
        level: INFO
        format: "MQTT connected"
  on_disconnect:
    - logger.log:
        level: INFO
        format: "MQTT disconnected"

b2500:
  - id: b2500_1
    generation: 2
    update_interval: 5s
    ble_client_id: b2500_ble_client_1

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Berlin"

ble_client:
  - mac_address: "7C:E7:12:19:A6:XX"
    id: b2500_ble_client_1
    on_connect:
      then:
        - logger.log:
            level: INFO
            format: "Connected to BLE device 1 (B2500)"
        - binary_sensor.template.publish:
            id: b2500_device_ble_ok_1
            state: ON
        - delay: 1s
        - b2500.set_datetime:
            id: b2500_1
            datetime: !lambda 'return id(sntp_time).now();'

    on_disconnect:
      then:
        - logger.log:
            level: INFO
            format: "Disconnected from BLE device 1 (B2500)"
        - binary_sensor.template.publish:
            id: b2500_device_ble_ok_1
            state: OFF

button:
  - platform: restart
    id: controller_restart
    name: "Restart Controller"
    command_topic: "b2500/restart/set"
  - platform: b2500
    b2500_id: b2500_1
    generation: 2
    reboot:
      id: b2500_button_reboot_1
      name: "B2500 - 1 - B2500: Reboot B2500"
      command_topic: "b2500/1/reboot/set"
    factory_reset:
      id: b2500_button_factory_reset_1
      name: "B2500 - 1 - B2500: Reset to Factory Settings"
      command_topic: "b2500/1/factory_settings/set"
      disabled_by_default: True
datetime:
  - platform: b2500
    b2500_id: b2500_1
    generation: 2
    timer1_start:
      id: b2500_timer1_time_start_1
      name: "B2500 - 1 - B2500: Timer 1 Start Time"
      state_topic: "b2500/1/timer/1/start"
      command_topic: "b2500/1/timer/1/start/set"
    timer1_end:
      id: b2500_timer1_time_end_1
      name: "B2500 - 1 - B2500: Timer 1 End Time"
      state_topic: "b2500/1/timer/1/end"
      command_topic: "b2500/1/timer/1/end/set"
    timer2_start:
      id: b2500_timer2_time_start_1
      name: "B2500 - 1 - B2500: Timer 2 Start Time"
      state_topic: "b2500/1/timer/2/start"
      command_topic: "b2500/1/timer/2/start/set"
    timer2_end:
      id: b2500_timer2_time_end_1
      name: "B2500 - 1 - B2500: Timer 2 End Time"
      state_topic: "b2500/1/timer/2/end"
      command_topic: "b2500/1/timer/2/end/set"
    timer3_start:
      id: b2500_timer3_time_start_1
      name: "B2500 - 1 - B2500: Timer 3 Start Time"
      state_topic: "b2500/1/timer/3/start"
      command_topic: "b2500/1/timer/3/start/set"
    timer3_end:
      id: b2500_timer3_time_end_1
      name: "B2500 - 1 - B2500: Timer 3 End Time"
      state_topic: "b2500/1/timer/3/end"
      command_topic: "b2500/1/timer/3/end/set"
    timer4_start:
      id: b2500_timer4_time_start_1
      name: "B2500 - 1 - B2500: Timer 4 Start Time"
      state_topic: "b2500/1/timer/4/start"
      command_topic: "b2500/1/timer/4/start/set"
    timer4_end:
      id: b2500_timer4_time_end_1
      name: "B2500 - 1 - B2500: Timer 4 End Time"
      state_topic: "b2500/1/timer/4/end"
      command_topic: "b2500/1/timer/4/end/set"
    timer5_start:
      id: b2500_timer5_time_start_1
      name: "B2500 - 1 - B2500: Timer 5 Start Time"
      state_topic: "b2500/1/timer/5/start"
      command_topic: "b2500/1/timer/5/start/set"
    timer5_end:
      id: b2500_timer5_time_end_1
      name: "B2500 - 1 - B2500: Timer 5 End Time"
      state_topic: "b2500/1/timer/5/end"
      command_topic: "b2500/1/timer/5/end/set"

number:
  - platform: b2500
    b2500_id: b2500_1
    generation: 2
    dod:
      id: b2500_battery_dod_1
      name: "B2500 - 1 - B2500: Depth of Discharge"
      state_topic: "b2500/1/battery/dod"
      command_topic: "b2500/1/battery/dod/set"
    timer1_output_power:
      id: b2500_timer1_power_1
      name: "B2500 - 1 - B2500: Timer 1 Output Power"
      state_topic: "b2500/1/timer/1/power"
      command_topic: "b2500/1/timer/1/power/set"
    timer2_output_power:
      id: b2500_timer2_power_1
      name: "B2500 - 1 - B2500: Timer 2 Output Power"
      state_topic: "b2500/1/timer/2/power"
      command_topic: "b2500/1/timer/2/power/set"
    timer3_output_power:
      id: b2500_timer3_power_1
      name: "B2500 - 1 - B2500: Timer 3 Output Power"
      state_topic: "b2500/1/timer/3/power"
      command_topic: "b2500/1/timer/3/power/set"
    timer4_output_power:
      id: b2500_timer4_power_1
      name: "B2500 - 1 - B2500: Timer 4 Output Power"
      state_topic: "b2500/1/timer/4/power"
      command_topic: "b2500/1/timer/4/power/set"
    timer5_output_power:
      id: b2500_timer5_power_1
      name: "B2500 - 1 - B2500: Timer 5 Output Power"
      state_topic: "b2500/1/timer/5/power"
      command_topic: "b2500/1/timer/5/power/set"


switch:
  - platform: ble_client
    ble_client_id: b2500_ble_client_1
    name: "B2500 - 1 - B2500: Bluetooth Enabled"
    id: b2500_bluetooth_enabled_1
    state_topic: "b2500/1/bluetooth/enabled"
    command_topic: "b2500/1/bluetooth/enabled/set"
    icon: mdi:bluetooth-connect
  - platform: b2500
    b2500_id: b2500_1
    generation: 2
    timer1_enabled:
      id: b2500_timer1_enabled_1
      name: "B2500 - 1 - B2500: Timer 1 Enabled"
      state_topic: "b2500/1/timer/1/enabled"
      command_topic: "b2500/1/timer/1/enabled/set"
    timer2_enabled:
      id: b2500_timer2_enabled_1
      name: "B2500 - 1 - B2500: Timer 2 Enabled"
      state_topic: "b2500/1/timer/2/enabled"
      command_topic: "b2500/1/timer/2/enabled/set"
    timer3_enabled:
      id: b2500_timer3_enabled_1
      name: "B2500 - 1 - B2500: Timer 3 Enabled"
      state_topic: "b2500/1/timer/3/enabled"
      command_topic: "b2500/1/timer/3/enabled/set"
    timer4_enabled:
      id: b2500_timer4_enabled_1
      name: "B2500 - 1 - B2500: Timer 4 Enabled"
      state_topic: "b2500/1/timer/4/enabled"
      command_topic: "b2500/1/timer/4/enabled/set"
    timer5_enabled:
      id: b2500_timer5_enabled_1
      name: "B2500 - 1 - B2500: Timer 5 Enabled"
      state_topic: "b2500/1/timer/5/enabled"
      command_topic: "b2500/1/timer/5/enabled/set"
    adaptive_mode:
      id: b2500_smartmeter_enabled_1
      name: "B2500 - 1 - B2500: SmartMeter Enabled"
      state_topic: "b2500/1/smartmeter/enabled"
      command_topic: "b2500/1/smartmeter/enabled/set"

select:
  - platform: b2500
    b2500_id: b2500_1
    generation: 2
    charge_mode:
      id: b2500_charge_mode_1
      name: "B2500 - 1 - B2500: Charge Mode"
      state_topic: "b2500/1/battery/charge_mode"
      command_topic: "b2500/1/battery/charge_mode/set"

text_sensor:
  - platform: template
    name: "B2500 - 1 - B2500: Generation"
    id: b2500_device_generation_1
    state_topic: "b2500/1/device/generation"
    icon: mdi:devices
  - platform: template
    name: "B2500 - 1 - B2500: Name"
    id: b2500_device_name_1
    state_topic: "b2500/1/device/name"
    icon: mdi:devices
  - platform: b2500
    b2500_id: b2500_1
    generation: 2
    device_type:
      name: "B2500 - 1 - B2500: Device Type"
      id: b2500_device_type_1
      state_topic: "b2500/1/device/type"
      icon: mdi:devices
    device_id:
      name: "B2500 - 1 - B2500: Device ID"
      state_topic: "b2500/1/device/id"
      id: b2500_device_id_1
      icon: mdi:identifier

    device_time:
      name: "B2500 - 1 - B2500: Device Time"
      id: b2500_device_time_1
      state_topic: "b2500/1/device/time"
      retain: false
      icon: mdi:clock

    firmware_version:
      name: "B2500 - 1 - B2500: Device Firmware Version"
      id: b2500_device_fw_version_1
      state_topic: "b2500/1/device/fw_version"
      icon: mdi:chip
    mac_address:
      name: "B2500 - 1 - B2500: MAC Address"
      id: b2500_device_ble_mac_1
      state_topic: "b2500/1/device/ble_mac"
      icon: mdi:network
    wifi_ssid:
      name: "B2500 - 1 - B2500: Wifi SSID"
      id: b2500_device_wifi_ssid_1
      state_topic: "b2500/1/device/wifi_ssid"
      icon: mdi:wifi
    fc41d_version:
      name: "B2500 - 1 - B2500: FC41D-Firmware"
      id: b2500_device_fc41d_fw_1
      state_topic: "b2500/1/device/fc41d_fw"
      icon: mdi:chip
    scene:
      name: "B2500 - 1 - B2500: Scene"
      id: b2500_device_scene_1
      state_topic: "b2500/1/device/scene"
      icon: mdi:theme-light-dark
    region:
      name: "B2500 - 1 - B2500: Region"
      id: b2500_device_region_1
      state_topic: "b2500/1/device/region"
      icon: mdi:earth
    last_response:
      name: "B2500 - 1 - B2500: Last Response"
      id: b2500_device_last_response_1
      state_topic: "b2500/1/device/last_response"
      retain: false
      icon: mdi:update
    cell_voltage:
      name: "B2500 - 1 - B2500: Cell Voltage"
      id: b2500_device_cell_voltage_1
      state_topic: "b2500/1/battery/cell_voltage"
      retain: false
      disabled_by_default: true
      icon: mdi:battery

binary_sensor:
  - platform: b2500
    b2500_id: b2500_1
    generation: 2
    in1_active:
      name: "B2500 - 1 - B2500: PV 1 - Active"
      id: b2500_pv1_active_1
      state_topic: "b2500/1/pv1/active"
      icon: mdi:solar-power
    in2_active:
      name: "B2500 - 1 - B2500: PV 2 - Active"
      id: b2500_pv2_active_1
      state_topic: "b2500/1/pv2/active"
      icon: mdi:solar-power
    in1_transparent:
      name: "B2500 - 1 - B2500: PV 1 - Transparent"
      id: b2500_pv1_transparent_1
      state_topic: "b2500/1/pv1/transparent"
      icon: mdi:transit-connection-variant
    in2_transparent:
      name: "B2500 - 1 - B2500: PV 2 - Transparent"
      id: b2500_pv2_transparent_1
      state_topic: "b2500/1/pv2/transparent"
      icon: mdi:transit-connection-variant
    wifi_connected:
      name: "B2500 - 1 - B2500: Wifi Connected"
      id: b2500_device_wifi_ok_1
      state_topic: "b2500/1/device/wifi_ok"
      icon: mdi:wifi
    mqtt_connected:
      name: "B2500 - 1 - B2500: MQTT Connected"
      id: b2500_device_mqtt_ok_1
      state_topic: "b2500/1/device/mqtt_ok"
      icon: mdi:cloud
    out1_active:
      name: "B2500 - 1 - B2500: Out 1 - Active"
      id: b2500_power1_active_1
      state_topic: "b2500/1/power1/active"
      icon: mdi:power-plug-battery
    out2_active:
      name: "B2500 - 1 - B2500: Out 2 - Active"
      id: b2500_power2_active_1
      state_topic: "b2500/1/power2/active"
      icon: mdi:power-plug-battery
    extern1_connected:
      name: "B2500 - 1 - B2500: Extension 1 connected"
      id: b2500_extern1_connected_1
      state_topic: "b2500/1/extern1/connected"
      icon: mdi:battery-plus
    extern2_connected:
      name: "B2500 - 1 - B2500: Extension 2 connected"
      id: b2500_extern2_connected_1
      state_topic: "b2500/1/extern2/connected"
      icon: mdi:battery-plus
    smart_meter_connected:
      name: "B2500 - 1 - B2500: SmartMeter Connected"
      id: b2500_smartmeter_connected_1
      state_topic: "b2500/1/smartmeter/connected"
      icon: mdi:meter-electric

  - platform: template
    name: "B2500 - 1 - B2500: BLE Connected"
    id: b2500_device_ble_ok_1
    state_topic: "b2500/1/device/ble_ok"
    icon: mdi:bluetooth

sensor:
  - platform: uptime
    name: Uptime Sensor
    filters:
      - lambda: return x / 3600.0;
    unit_of_measurement: "hours"
    accuracy_decimals: 2
    state_topic: "b2500/esp32/uptime"
    retain: false
  - platform: b2500
    b2500_id: b2500_1
    generation: 2
    in1_power:
      name: "B2500 - 1 - B2500: In 1 - Power"
      id: b2500_in1_power_1
      state_topic: "b2500/1/pv1/power"
      retain: false
      device_class: power
      icon: mdi:solar-power
    in2_power:
      name: "B2500 - 1 - B2500: In 2 - Power"
      id: b2500_in2_power_1
      state_topic: "b2500/1/pv2/power"
      retain: false
      device_class: power
      icon: mdi:solar-power
    in_total_power:
      name: "B2500 - 1 - B2500: Total Power In"
      id: b2500_total_power_in_1
      state_topic: "b2500/1/pv/power"
      retain: false
      device_class: power
    out1_power:
      name: "B2500 - 1 - B2500: Out 1 - Power"
      id: b2500_out1_power_1
      state_topic: "b2500/1/power1/power"
      retain: false
      device_class: power
    out2_power:
      name: "B2500 - 1 - B2500: Out 2 - Power"
      id: b2500_out2_power_1
      state_topic: "b2500/1/power2/power"
      retain: false
      device_class: power
    out_total_power:
      name: "B2500 - 1 - B2500: Total Power Out"
      id: b2500_total_power_out_1
      state_topic: "b2500/1/power/power"
      retain: false
      device_class: power
    soc:
      name: "B2500 - 1 - B2500: Battery Level"
      id: b2500_battery_remaining_percent_1
      state_topic: "b2500/1/battery/remaining_percent"
      retain: false
    capacity:
      name: "B2500 - 1 - B2500: Battery Capacity"
      id: b2500_battery_remaining_capacity_1
      state_topic: "b2500/1/battery/remaining_capacity"
      retain: false
      device_class: energy
    temperature_low:
      name: "B2500 - 1 - B2500: Temperature 1"
      id: b2500_device_temperature1_1
      state_topic: "b2500/1/device/temp1"
      retain: false
      device_class: temperature
      icon: mdi:thermometer
    temperature_high:
      name: "B2500 - 1 - B2500: Temperature 2"
      id: b2500_device_temperature2_1
      state_topic: "b2500/1/device/temp2"
      retain: false
      device_class: temperature
      icon: mdi:thermometer
    adaptive_power_out:
      name: "B2500 - 1 - B2500: Smartmeter Power Out"
      id: b2500_smartmeter_power_out_1
      state_topic: "b2500/1/smartmeter/out"
      retain: false
      device_class: power
      icon: mdi:home-lightning-bolt
    smart_meter_reading:
      name: "B2500 - 1 - B2500: Smartmeter Value"
      id: b2500_smartmeter_value_1
      state_topic: "b2500/1/smartmeter/value"
      retain: false
      device_class: power
      icon: mdi:meter-electric
    daily_total_battery_charge:
      name: "B2500 - 1 - B2500: Daily Total Battery Charge"
      id: b2500_daily_total_battery_charge_1
      state_topic: "b2500/1/battery/daily_total_charge"
      device_class: energy
      unit_of_measurement: Wh
      accuracy_decimals: 0
    daily_total_battery_discharge:
      name: "B2500 - 1 - B2500: Daily Total Battery Discharge"
      id: b2500_daily_total_battery_discharge_1
      state_topic: "b2500/1/battery/daily_total_discharge"
      device_class: energy
      unit_of_measurement: Wh
      accuracy_decimals: 0
    daily_total_load_charge:
      name: "B2500 - 1 - B2500: Daily Total Load Charge"
      id: b2500_daily_total_load_charge_1
      state_topic: "b2500/1/load/daily_total_charge"
      device_class: energy
      unit_of_measurement: Wh
      accuracy_decimals: 0
    daily_total_load_discharge:
      name: "B2500 - 1 - B2500: Daily Total Load Discharge"
      id: b2500_daily_total_load_discharge_1
      state_topic: "b2500/1/load/daily_total_discharge"
      device_class: energy
      unit_of_measurement: Wh
      accuracy_decimals: 0
  - platform: total_daily_energy
    name: "B2500 - 1 - B2500: Total Daily Energy In"
    id: b2500_total_daily_energy_in_1
    state_topic: "b2500/1/pv/energy"
    power_id: b2500_total_power_in_1
    unit_of_measurement: kWh
    method: left
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: total_daily_energy
    name: "B2500 - 1 - B2500: Total Daily Energy Out"
    id: b2500_total_daily_energy_out_1
    state_topic: "b2500/1/power/energy"
    power_id: b2500_total_power_out_1
    unit_of_measurement: kWh
    method: left
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
```
