### ISSUE TITLE
Firmware build     Error wiggly-clumsy-dog-830

### ISSUE THREAD

**Issue by Jeba0815** [tomquist/esphome-b2500#125]
Hallo

Ich bekomme es nicht hin, dass die  Firmware mit einem Grüne Haken versehen ist. Es schlägt immer wieder fehl.
Kann mir jemand helfen.

Nach dieser Anleitung hab ich das gemacht. Auch mir verschieden Einstellungen schon gespielt.

[ESP32-einrichten.pdf](https://github.com/user-attachments/files/20102945/ESP32-einrichten.pdf)

B2500 V1
B2500 V2

Das ganze soll via MQTT in den Iobroker danach kommen.

Run exit 1
Error: Process completed with exit code 1.

SSID und Passwörter habe ich unten mir "xxxxxxx" überschrieben. Nicht wundern

```
esphome:
  name: "b2500"
  friendly_name: "b2500"
  on_boot:
    priority: -100
    then:
      - lambda: id(b2500_device_generation_1).publish_state("1");
      - lambda: id(b2500_device_name_1).publish_state("Speicher 1");
      - lambda: id(b2500_device_generation_2).publish_state("2");
      - lambda: id(b2500_device_name_2).publish_state("Speicher 2");
api:

esp32:
  board: "ESP32-s3"
  variant: "esp32s3"
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      COMPILER_OPTIMIZATION_SIZE: y

# Enable logging
logger:
  level: INFO
ota:
  - platform: esphome
    password: "my_ota_password"
external_components:
  - source:
      type: git
      url: https://github.com/tomquist/esphome-b2500
      ref: "main"
    refresh: 0s
    components: [b2500]

wifi:
  ssid: "WLANBA"
  password: "xxxxxxxxx"
  reboot_timeout: 0s
  fast_connect: True
  on_connect:
    - logger.log:
        level: INFO
        format: "Connected to WiFi. Starting BLE scan."
  on_disconnect:
    - logger.log:
        level: INFO
        format: "Disconnected from WiFi. Stopping BLE scan."
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome-b2500"
web_server:
  port: 80
  ota: false
  js_include: "./v2/www.js"
  js_url: ""
  version: 2
captive_portal:
mqtt:
  id: mqtt_client
  broker: "192.268.178.41"
  port: 1883
  username: "xxxxx"
  password: "xxxxx"
  discovery: True
  reboot_timeout: 0s
  topic_prefix: "b2500"
  log_topic: "b2500/debug"
  on_connect:
    - logger.log:
        level: INFO
        format: "MQTT connected"
  on_disconnect:
    - logger.log:
        level: INFO
        format: "MQTT disconnected"

b2500:
  - id: b2500_1
    generation: 1
    update_interval: 5s
    ble_client_id: b2500_ble_client_1
  - id: b2500_2
    generation: 2
    update_interval: 5s
    ble_client_id: b2500_ble_client_2

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Berlin"

ble_client:
  - mac_address: "24:19:72:0d:40:fe"
    id: b2500_ble_client_1
    on_connect:
      then:
        - logger.log:
            level: INFO
            format: "Connected to BLE device 1 (Speicher 1)"
        - binary_sensor.template.publish:
            id: b2500_device_ble_ok_1
            state: ON
        - delay: 1s
        - b2500.set_datetime:
            id: b2500_1
            datetime: !lambda 'return id(sntp_time).now();'

    on_disconnect:
      then:
        - logger.log:
            level: INFO
            format: "Disconnected from BLE device 1 (Speicher 1)"
        - binary_sensor.template.publish:
            id: b2500_device_ble_ok_1
            state: OFF
  - mac_address: "7c:e7:12:19:a2:38"
    id: b2500_ble_client_2
    on_connect:
      then:
        - logger.log:
            level: INFO
            format: "Connected to BLE device 2 (Speicher 2)"
        - binary_sensor.template.publish:
            id: b2500_device_ble_ok_2
            state: ON
        - delay: 1s
        - b2500.set_datetime:
            id: b2500_2
            datetime: !lambda 'return id(sntp_time).now();'

    on_disconnect:
      then:
        - logger.log:
            level: INFO
            format: "Disconnected from BLE device 2 (Speicher 2)"
        - binary_sensor.template.publish:
            id: b2500_device_ble_ok_2
            state: OFF

button:
  - platform: restart
    id: controller_restart
    name: "Restart Controller"
    command_topic: "b2500/restart/set"
  - platform: b2500
    b2500_id: b2500_1
    generation: 1
    reboot:
      id: b2500_button_reboot_1
      name: "B2500 - 1 - Speicher 1: Reboot B2500"
      command_topic: "b2500/1/reboot/set"
    factory_reset:
      id: b2500_button_factory_reset_1
      name: "B2500 - 1 - Speicher 1: Reset to Factory Settings"
      command_topic: "b2500/1/factory_settings/set"
      disabled_by_default: True
  - platform: b2500
    b2500_id: b2500_2
    generation: 2
    reboot:
      id: b2500_button_reboot_2
      name: "B2500 - 2 - Speicher 2: Reboot B2500"
      command_topic: "b2500/2/reboot/set"
    factory_reset:
      id: b2500_button_factory_reset_2
      name: "B2500 - 2 - Speicher 2: Reset to Factory Settings"
      command_topic: "b2500/2/factory_settings/set"
      disabled_by_default: True
datetime:
  - platform: b2500
    b2500_id: b2500_2
    generation: 2
    timer1_start:
      id: b2500_timer1_time_start_2
      name: "B2500 - 2 - Speicher 2: Timer 1 Start Time"
      state_topic: "b2500/2/timer/1/start"
      command_topic: "b2500/2/timer/1/start/set"
    timer1_end:
      id: b2500_timer1_time_end_2
      name: "B2500 - 2 - Speicher 2: Timer 1 End Time"
      state_topic: "b2500/2/timer/1/end"
      command_topic: "b2500/2/timer/1/end/set"
    timer2_start:
      id: b2500_timer2_time_start_2
      name: "B2500 - 2 - Speicher 2: Timer 2 Start Time"
      state_topic: "b2500/2/timer/2/start"
      command_topic: "b2500/2/timer/2/start/set"
    timer2_end:
      id: b2500_timer2_time_end_2
      name: "B2500 - 2 - Speicher 2: Timer 2 End Time"
      state_topic: "b2500/2/timer/2/end"
      command_topic: "b2500/2/timer/2/end/set"
    timer3_start:
      id: b2500_timer3_time_start_2
      name: "B2500 - 2 - Speicher 2: Timer 3 Start Time"
      state_topic: "b2500/2/timer/3/start"
      command_topic: "b2500/2/timer/3/start/set"
    timer3_end:
      id: b2500_timer3_time_end_2
      name: "B2500 - 2 - Speicher 2: Timer 3 End Time"
      state_topic: "b2500/2/timer/3/end"
      command_topic: "b2500/2/timer/3/end/set"
    timer4_start:
      id: b2500_timer4_time_start_2
      name: "B2500 - 2 - Speicher 2: Timer 4 Start Time"
      state_topic: "b2500/2/timer/4/start"
      command_topic: "b2500/2/timer/4/start/set"
    timer4_end:
      id: b2500_timer4_time_end_2
      name: "B2500 - 2 - Speicher 2: Timer 4 End Time"
      state_topic: "b2500/2/timer/4/end"
      command_topic: "b2500/2/timer/4/end/set"
    timer5_start:
      id: b2500_timer5_time_start_2
      name: "B2500 - 2 - Speicher 2: Timer 5 Start Time"
      state_topic: "b2500/2/timer/5/start"
      command_topic: "b2500/2/timer/5/start/set"
    timer5_end:
      id: b2500_timer5_time_end_2
      name: "B2500 - 2 - Speicher 2: Timer 5 End Time"
      state_topic: "b2500/2/timer/5/end"
      command_topic: "b2500/2/timer/5/end/set"

number:
  - platform: b2500
    b2500_id: b2500_1
    generation: 1
    discharge_threshold:
      id: b2500_battery_discharge_threshold_1
      name: "B2500 - 1 - Speicher 1: Discharge Threshold"
      state_topic: "b2500/1/battery/discharge_threshold"
      command_topic: "b2500/1/battery/discharge_threshold/set"
    dod:
      id: b2500_battery_dod_1
      name: "B2500 - 1 - Speicher 1: Depth of Discharge"
      state_topic: "b2500/1/battery/dod"
      command_topic: "b2500/1/battery/dod/set"
  - platform: b2500
    b2500_id: b2500_2
    generation: 2
    dod:
      id: b2500_battery_dod_2
      name: "B2500 - 2 - Speicher 2: Depth of Discharge"
      state_topic: "b2500/2/battery/dod"
      command_topic: "b2500/2/battery/dod/set"
    timer1_output_power:
      id: b2500_timer1_power_2
      name: "B2500 - 2 - Speicher 2: Timer 1 Output Power"
      state_topic: "b2500/2/timer/1/power"
      command_topic: "b2500/2/timer/1/power/set"
    timer2_output_power:
      id: b2500_timer2_power_2
      name: "B2500 - 2 - Speicher 2: Timer 2 Output Power"
      state_topic: "b2500/2/timer/2/power"
      command_topic: "b2500/2/timer/2/power/set"
    timer3_output_power:
      id: b2500_timer3_power_2
      name: "B2500 - 2 - Speicher 2: Timer 3 Output Power"
      state_topic: "b2500/2/timer/3/power"
      command_topic: "b2500/2/timer/3/power/set"
    timer4_output_power:
      id: b2500_timer4_power_2
      name: "B2500 - 2 - Speicher 2: Timer 4 Output Power"
      state_topic: "b2500/2/timer/4/power"
      command_topic: "b2500/2/timer/4/power/set"
    timer5_output_power:
      id: b2500_timer5_power_2
      name: "B2500 - 2 - Speicher 2: Timer 5 Output Power"
      state_topic: "b2500/2/timer/5/power"
      command_topic: "b2500/2/timer/5/power/set"


switch:
  - platform: ble_client
    ble_client_id: b2500_ble_client_1
    name: "B2500 - 1 - Speicher 1: Bluetooth Enabled"
    id: b2500_bluetooth_enabled_1
    state_topic: "b2500/1/bluetooth/enabled"
    command_topic: "b2500/1/bluetooth/enabled/set"
    icon: mdi:bluetooth-connect
  - platform: b2500
    b2500_id: b2500_1
    generation: 1
    out1:
      id: b2500_out1_active_1
      name: "B2500 - 1 - Speicher 1: Out 1 - Active"
      state_topic: "b2500/1/power1/enabled"
      command_topic: "b2500/1/power1/enabled/set"
    out2:
      id: b2500_out2_active_1
      name: "B2500 - 1 - Speicher 1: Out 2 - Active"
      state_topic: "b2500/1/power2/enabled"
      command_topic: "b2500/1/power2/enabled/set"
  - platform: ble_client
    ble_client_id: b2500_ble_client_2
    name: "B2500 - 2 - Speicher 2: Bluetooth Enabled"
    id: b2500_bluetooth_enabled_2
    state_topic: "b2500/2/bluetooth/enabled"
    command_topic: "b2500/2/bluetooth/enabled/set"
    icon: mdi:bluetooth-connect
  - platform: b2500
    b2500_id: b2500_2
    generation: 2
    timer1_enabled:
      id: b2500_timer1_enabled_2
      name: "B2500 - 2 - Speicher 2: Timer 1 Enabled"
      state_topic: "b2500/2/timer/1/enabled"
      command_topic: "b2500/2/timer/1/enabled/set"
    timer2_enabled:
      id: b2500_timer2_enabled_2
      name: "B2500 - 2 - Speicher 2: Timer 2 Enabled"
      state_topic: "b2500/2/timer/2/enabled"
      command_topic: "b2500/2/timer/2/enabled/set"
    timer3_enabled:
      id: b2500_timer3_enabled_2
      name: "B2500 - 2 - Speicher 2: Timer 3 Enabled"
      state_topic: "b2500/2/timer/3/enabled"
      command_topic: "b2500/2/timer/3/enabled/set"
    timer4_enabled:
      id: b2500_timer4_enabled_2
      name: "B2500 - 2 - Speicher 2: Timer 4 Enabled"
      state_topic: "b2500/2/timer/4/enabled"
      command_topic: "b2500/2/timer/4/enabled/set"
    timer5_enabled:
      id: b2500_timer5_enabled_2
      name: "B2500 - 2 - Speicher 2: Timer 5 Enabled"
      state_topic: "b2500/2/timer/5/enabled"
      command_topic: "b2500/2/timer/5/enabled/set"
    adaptive_mode:
      id: b2500_smartmeter_enabled_2
      name: "B2500 - 2 - Speicher 2: SmartMeter Enabled"
      state_topic: "b2500/2/smartmeter/enabled"
      command_topic: "b2500/2/smartmeter/enabled/set"

select:
  - platform: b2500
    b2500_id: b2500_1
    generation: 1
    charge_mode:
      id: b2500_charge_mode_1
      name: "B2500 - 1 - Speicher 1: Charge Mode"
      state_topic: "b2500/1/battery/charge_mode"
      command_topic: "b2500/1/battery/charge_mode/set"
  - platform: b2500
    b2500_id: b2500_2
    generation: 2
    charge_mode:
      id: b2500_charge_mode_2
      name: "B2500 - 2 - Speicher 2: Charge Mode"
      state_topic: "b2500/2/battery/charge_mode"
      command_topic: "b2500/2/battery/charge_mode/set"

text_sensor:
  - platform: template
    name: "B2500 - 1 - Speicher 1: Generation"
    id: b2500_device_generation_1
    state_topic: "b2500/1/device/generation"
    icon: mdi:devices
  - platform: template
    name: "B2500 - 1 - Speicher 1: Name"
    id: b2500_device_name_1
    state_topic: "b2500/1/device/name"
    icon: mdi:devices
  - platform: b2500
    b2500_id: b2500_1
    generation: 1
    device_type:
      name: "B2500 - 1 - Speicher 1: Device Type"
      id: b2500_device_type_1
      state_topic: "b2500/1/device/type"
      icon: mdi:devices
    device_id:
      name: "B2500 - 1 - Speicher 1: Device ID"
      state_topic: "b2500/1/device/id"
      id: b2500_device_id_1
      icon: mdi:identifier

    firmware_version:
      name: "B2500 - 1 - Speicher 1: Device Firmware Version"
      id: b2500_device_fw_version_1
      state_topic: "b2500/1/device/fw_version"
      icon: mdi:chip
    mac_address:
      name: "B2500 - 1 - Speicher 1: MAC Address"
      id: b2500_device_ble_mac_1
      state_topic: "b2500/1/device/ble_mac"
      icon: mdi:network
    wifi_ssid:
      name: "B2500 - 1 - Speicher 1: Wifi SSID"
      id: b2500_device_wifi_ssid_1
      state_topic: "b2500/1/device/wifi_ssid"
      icon: mdi:wifi
    fc41d_version:
      name: "B2500 - 1 - Speicher 1: FC41D-Firmware"
      id: b2500_device_fc41d_fw_1
      state_topic: "b2500/1/device/fc41d_fw"
      icon: mdi:chip
    scene:
      name: "B2500 - 1 - Speicher 1: Scene"
      id: b2500_device_scene_1
      state_topic: "b2500/1/device/scene"
      icon: mdi:theme-light-dark
    region:
      name: "B2500 - 1 - Speicher 1: Region"
      id: b2500_device_region_1
      state_topic: "b2500/1/device/region"
      icon: mdi:earth
    last_response:
      name: "B2500 - 1 - Speicher 1: Last Response"
      id: b2500_device_last_response_1
      state_topic: "b2500/1/device/last_response"
      retain: false
      icon: mdi:update
    cell_voltage:
      name: "B2500 - 1 - Speicher 1: Cell Voltage"
      id: b2500_device_cell_voltage_1
      state_topic: "b2500/1/battery/cell_voltage"
      retain: false
      disabled_by_default: true
      icon: mdi:battery
  - platform: template
    name: "B2500 - 2 - Speicher 2: Generation"
    id: b2500_device_generation_2
    state_topic: "b2500/2/device/generation"
    icon: mdi:devices
  - platform: template
    name: "B2500 - 2 - Speicher 2: Name"
    id: b2500_device_name_2
    state_topic: "b2500/2/device/name"
    icon: mdi:devices
  - platform: b2500
    b2500_id: b2500_2
    generation: 2
    device_type:
      name: "B2500 - 2 - Speicher 2: Device Type"
      id: b2500_device_type_2
      state_topic: "b2500/2/device/type"
      icon: mdi:devices
    device_id:
      name: "B2500 - 2 - Speicher 2: Device ID"
      state_topic: "b2500/2/device/id"
      id: b2500_device_id_2
      icon: mdi:identifier

    device_time:
      name: "B2500 - 2 - Speicher 2: Device Time"
      id: b2500_device_time_2
      state_topic: "b2500/2/device/time"
      retain: false
      icon: mdi:clock

    firmware_version:
      name: "B2500 - 2 - Speicher 2: Device Firmware Version"
      id: b2500_device_fw_version_2
      state_topic: "b2500/2/device/fw_version"
      icon: mdi:chip
    mac_address:
      name: "B2500 - 2 - Speicher 2: MAC Address"
      id: b2500_device_ble_mac_2
      state_topic: "b2500/2/device/ble_mac"
      icon: mdi:network
    wifi_ssid:
      name: "B2500 - 2 - Speicher 2: Wifi SSID"
      id: b2500_device_wifi_ssid_2
      state_topic: "b2500/2/device/wifi_ssid"
      icon: mdi:wifi
    fc41d_version:
      name: "B2500 - 2 - Speicher 2: FC41D-Firmware"
      id: b2500_device_fc41d_fw_2
      state_topic: "b2500/2/device/fc41d_fw"
      icon: mdi:chip
    scene:
      name: "B2500 - 2 - Speicher 2: Scene"
      id: b2500_device_scene_2
      state_topic: "b2500/2/device/scene"
      icon: mdi:theme-light-dark
    region:
      name: "B2500 - 2 - Speicher 2: Region"
      id: b2500_device_region_2
      state_topic: "b2500/2/device/region"
      icon: mdi:earth
    last_response:
      name: "B2500 - 2 - Speicher 2: Last Response"
      id: b2500_device_last_response_2
      state_topic: "b2500/2/device/last_response"
      retain: false
      icon: mdi:update
    cell_voltage:
      name: "B2500 - 2 - Speicher 2: Cell Voltage"
      id: b2500_device_cell_voltage_2
      state_topic: "b2500/2/battery/cell_voltage"
      retain: false
      disabled_by_default: true
      icon: mdi:battery

binary_sensor:
  - platform: b2500
    b2500_id: b2500_1
    generation: 1
    in1_active:
      name: "B2500 - 1 - Speicher 1: PV 1 - Active"
      id: b2500_pv1_active_1
      state_topic: "b2500/1/pv1/active"
      icon: mdi:solar-power
    in2_active:
      name: "B2500 - 1 - Speicher 1: PV 2 - Active"
      id: b2500_pv2_active_1
      state_topic: "b2500/1/pv2/active"
      icon: mdi:solar-power
    in1_transparent:
      name: "B2500 - 1 - Speicher 1: PV 1 - Transparent"
      id: b2500_pv1_transparent_1
      state_topic: "b2500/1/pv1/transparent"
      icon: mdi:transit-connection-variant
    in2_transparent:
      name: "B2500 - 1 - Speicher 1: PV 2 - Transparent"
      id: b2500_pv2_transparent_1
      state_topic: "b2500/1/pv2/transparent"
      icon: mdi:transit-connection-variant
    wifi_connected:
      name: "B2500 - 1 - Speicher 1: Wifi Connected"
      id: b2500_device_wifi_ok_1
      state_topic: "b2500/1/device/wifi_ok"
      icon: mdi:wifi
    mqtt_connected:
      name: "B2500 - 1 - Speicher 1: MQTT Connected"
      id: b2500_device_mqtt_ok_1
      state_topic: "b2500/1/device/mqtt_ok"
      icon: mdi:cloud
    out1_active:
      name: "B2500 - 1 - Speicher 1: Out 1 - Active"
      id: b2500_power1_active_1
      state_topic: "b2500/1/power1/active"
      icon: mdi:power-plug-battery
    out2_active:
      name: "B2500 - 1 - Speicher 1: Out 2 - Active"
      id: b2500_power2_active_1
      state_topic: "b2500/1/power2/active"
      icon: mdi:power-plug-battery
    extern1_connected:
      name: "B2500 - 1 - Speicher 1: Extension 1 connected"
      id: b2500_extern1_connected_1
      state_topic: "b2500/1/extern1/connected"
      icon: mdi:battery-plus
    extern2_connected:
      name: "B2500 - 1 - Speicher 1: Extension 2 connected"
      id: b2500_extern2_connected_1
      state_topic: "b2500/1/extern2/connected"
      icon: mdi:battery-plus

  - platform: template
    name: "B2500 - 1 - Speicher 1: BLE Connected"
    id: b2500_device_ble_ok_1
    state_topic: "b2500/1/device/ble_ok"
    icon: mdi:bluetooth
  - platform: b2500
    b2500_id: b2500_2
    generation: 2
    in1_active:
      name: "B2500 - 2 - Speicher 2: PV 1 - Active"
      id: b2500_pv1_active_2
      state_topic: "b2500/2/pv1/active"
      icon: mdi:solar-power
    in2_active:
      name: "B2500 - 2 - Speicher 2: PV 2 - Active"
      id: b2500_pv2_active_2
      state_topic: "b2500/2/pv2/active"
      icon: mdi:solar-power
    in1_transparent:
      name: "B2500 - 2 - Speicher 2: PV 1 - Transparent"
      id: b2500_pv1_transparent_2
      state_topic: "b2500/2/pv1/transparent"
      icon: mdi:transit-connection-variant
    in2_transparent:
      name: "B2500 - 2 - Speicher 2: PV 2 - Transparent"
      id: b2500_pv2_transparent_2
      state_topic: "b2500/2/pv2/transparent"
      icon: mdi:transit-connection-variant
    wifi_connected:
      name: "B2500 - 2 - Speicher 2: Wifi Connected"
      id: b2500_device_wifi_ok_2
      state_topic: "b2500/2/device/wifi_ok"
      icon: mdi:wifi
    mqtt_connected:
      name: "B2500 - 2 - Speicher 2: MQTT Connected"
      id: b2500_device_mqtt_ok_2
      state_topic: "b2500/2/device/mqtt_ok"
      icon: mdi:cloud
    out1_active:
      name: "B2500 - 2 - Speicher 2: Out 1 - Active"
      id: b2500_power1_active_2
      state_topic: "b2500/2/power1/active"
      icon: mdi:power-plug-battery
    out2_active:
      name: "B2500 - 2 - Speicher 2: Out 2 - Active"
      id: b2500_power2_active_2
      state_topic: "b2500/2/power2/active"
      icon: mdi:power-plug-battery
    extern1_connected:
      name: "B2500 - 2 - Speicher 2: Extension 1 connected"
      id: b2500_extern1_connected_2
      state_topic: "b2500/2/extern1/connected"
      icon: mdi:battery-plus
    extern2_connected:
      name: "B2500 - 2 - Speicher 2: Extension 2 connected"
      id: b2500_extern2_connected_2
      state_topic: "b2500/2/extern2/connected"
      icon: mdi:battery-plus
    smart_meter_connected:
      name: "B2500 - 2 - Speicher 2: SmartMeter Connected"
      id: b2500_smartmeter_connected_2
      state_topic: "b2500/2/smartmeter/connected"
      icon: mdi:meter-electric

  - platform: template
    name: "B2500 - 2 - Speicher 2: BLE Connected"
    id: b2500_device_ble_ok_2
    state_topic: "b2500/2/device/ble_ok"
    icon: mdi:bluetooth

sensor:
  - platform: uptime
    name: Uptime Sensor
    filters:
      - lambda: return x / 3600.0;
    unit_of_measurement: "hours"
    accuracy_decimals: 2
    state_topic: "b2500/esp32/uptime"
    retain: false
  - platform: b2500
    b2500_id: b2500_1
    generation: 1
    in1_power:
      name: "B2500 - 1 - Speicher 1: In 1 - Power"
      id: b2500_in1_power_1
      state_topic: "b2500/1/pv1/power"
      retain: false
      device_class: power
      icon: mdi:solar-power
    in2_power:
      name: "B2500 - 1 - Speicher 1: In 2 - Power"
      id: b2500_in2_power_1
      state_topic: "b2500/1/pv2/power"
      retain: false
      device_class: power
      icon: mdi:solar-power
    in_total_power:
      name: "B2500 - 1 - Speicher 1: Total Power In"
      id: b2500_total_power_in_1
      state_topic: "b2500/1/pv/power"
      retain: false
      device_class: power
      on_value:
        then:
          - script.execute: b2500_update_total_power_in
    out1_power:
      name: "B2500 - 1 - Speicher 1: Out 1 - Power"
      id: b2500_out1_power_1
      state_topic: "b2500/1/power1/power"
      retain: false
      device_class: power
    out2_power:
      name: "B2500 - 1 - Speicher 1: Out 2 - Power"
      id: b2500_out2_power_1
      state_topic: "b2500/1/power2/power"
      retain: false
      device_class: power
    out_total_power:
      name: "B2500 - 1 - Speicher 1: Total Power Out"
      id: b2500_total_power_out_1
      state_topic: "b2500/1/power/power"
      retain: false
      device_class: power
      on_value:
        then:
          - script.execute: b2500_update_total_power_out
    soc:
      name: "B2500 - 1 - Speicher 1: Battery Level"
      id: b2500_battery_remaining_percent_1
      state_topic: "b2500/1/battery/remaining_percent"
      retain: false
    capacity:
      name: "B2500 - 1 - Speicher 1: Battery Capacity"
      id: b2500_battery_remaining_capacity_1
      state_topic: "b2500/1/battery/remaining_capacity"
      retain: false
      device_class: energy
      on_value:
        then:
          - script.execute: b2500_update_total_remaining_capacity
    temperature_low:
      name: "B2500 - 1 - Speicher 1: Temperature 1"
      id: b2500_device_temperature1_1
      state_topic: "b2500/1/device/temp1"
      retain: false
      device_class: temperature
      icon: mdi:thermometer
    temperature_high:
      name: "B2500 - 1 - Speicher 1: Temperature 2"
      id: b2500_device_temperature2_1
      state_topic: "b2500/1/device/temp2"
      retain: false
      device_class: temperature
      icon: mdi:thermometer
  - platform: total_daily_energy
    name: "B2500 - 1 - Speicher 1: Total Daily Energy In"
    id: b2500_total_daily_energy_in_1
    state_topic: "b2500/1/pv/energy"
    power_id: b2500_total_power_in_1
    unit_of_measurement: kWh
    method: left
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    on_value:
      then:
        - script.execute: b2500_update_total_daily_energy_in
  - platform: total_daily_energy
    name: "B2500 - 1 - Speicher 1: Total Daily Energy Out"
    id: b2500_total_daily_energy_out_1
    state_topic: "b2500/1/power/energy"
    power_id: b2500_total_power_out_1
    unit_of_measurement: kWh
    method: left
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    on_value:
      then:
        - script.execute: b2500_update_total_daily_energy_out
  - platform: b2500
    b2500_id: b2500_2
    generation: 2
    in1_power:
      name: "B2500 - 2 - Speicher 2: In 1 - Power"
      id: b2500_in1_power_2
      state_topic: "b2500/2/pv1/power"
      retain: false
      device_class: power
      icon: mdi:solar-power
    in2_power:
      name: "B2500 - 2 - Speicher 2: In 2 - Power"
      id: b2500_in2_power_2
      state_topic: "b2500/2/pv2/power"
      retain: false
      device_class: power
      icon: mdi:solar-power
    in_total_power:
      name: "B2500 - 2 - Speicher 2: Total Power In"
      id: b2500_total_power_in_2
      state_topic: "b2500/2/pv/power"
      retain: false
      device_class: power
      on_value:
        then:
          - script.execute: b2500_update_total_power_in
    out1_power:
      name: "B2500 - 2 - Speicher 2: Out 1 - Power"
      id: b2500_out1_power_2
      state_topic: "b2500/2/power1/power"
      retain: false
      device_class: power
    out2_power:
      name: "B2500 - 2 - Speicher 2: Out 2 - Power"
      id: b2500_out2_power_2
      state_topic: "b2500/2/power2/power"
      retain: false
      device_class: power
    out_total_power:
      name: "B2500 - 2 - Speicher 2: Total Power Out"
      id: b2500_total_power_out_2
      state_topic: "b2500/2/power/power"
      retain: false
      device_class: power
      on_value:
        then:
          - script.execute: b2500_update_total_power_out
    soc:
      name: "B2500 - 2 - Speicher 2: Battery Level"
      id: b2500_battery_remaining_percent_2
      state_topic: "b2500/2/battery/remaining_percent"
      retain: false
    capacity:
      name: "B2500 - 2 - Speicher 2: Battery Capacity"
      id: b2500_battery_remaining_capacity_2
      state_topic: "b2500/2/battery/remaining_capacity"
      retain: false
      device_class: energy
      on_value:
        then:
          - script.execute: b2500_update_total_remaining_capacity
    temperature_low:
      name: "B2500 - 2 - Speicher 2: Temperature 1"
      id: b2500_device_temperature1_2
      state_topic: "b2500/2/device/temp1"
      retain: false
      device_class: temperature
      icon: mdi:thermometer
    temperature_high:
      name: "B2500 - 2 - Speicher 2: Temperature 2"
      id: b2500_device_temperature2_2
      state_topic: "b2500/2/device/temp2"
      retain: false
      device_class: temperature
      icon: mdi:thermometer
    adaptive_power_out:
      name: "B2500 - 2 - Speicher 2: Smartmeter Power Out"
      id: b2500_smartmeter_power_out_2
      state_topic: "b2500/2/smartmeter/out"
      retain: false
      device_class: power
      icon: mdi:home-lightning-bolt
    smart_meter_reading:
      name: "B2500 - 2 - Speicher 2: Smartmeter Value"
      id: b2500_smartmeter_value_2
      state_topic: "b2500/2/smartmeter/value"
      retain: false
      device_class: power
      icon: mdi:meter-electric
    daily_total_battery_charge:
      name: "B2500 - 2 - Speicher 2: Daily Total Battery Charge"
      id: b2500_daily_total_battery_charge_2
      state_topic: "b2500/2/battery/daily_total_charge"
      device_class: energy
      unit_of_measurement: Wh
      accuracy_decimals: 0
    daily_total_battery_discharge:
      name: "B2500 - 2 - Speicher 2: Daily Total Battery Discharge"
      id: b2500_daily_total_battery_discharge_2
      state_topic: "b2500/2/battery/daily_total_discharge"
      device_class: energy
      unit_of_measurement: Wh
      accuracy_decimals: 0
    daily_total_load_charge:
      name: "B2500 - 2 - Speicher 2: Daily Total Load Charge"
      id: b2500_daily_total_load_charge_2
      state_topic: "b2500/2/load/daily_total_charge"
      device_class: energy
      unit_of_measurement: Wh
      accuracy_decimals: 0
    daily_total_load_discharge:
      name: "B2500 - 2 - Speicher 2: Daily Total Load Discharge"
      id: b2500_daily_total_load_discharge_2
      state_topic: "b2500/2/load/daily_total_discharge"
      device_class: energy
      unit_of_measurement: Wh
      accuracy_decimals: 0
  - platform: total_daily_energy
    name: "B2500 - 2 - Speicher 2: Total Daily Energy In"
    id: b2500_total_daily_energy_in_2
    state_topic: "b2500/2/pv/energy"
    power_id: b2500_total_power_in_2
    unit_of_measurement: kWh
    method: left
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    on_value:
      then:
        - script.execute: b2500_update_total_daily_energy_in
  - platform: total_daily_energy
    name: "B2500 - 2 - Speicher 2: Total Daily Energy Out"
    id: b2500_total_daily_energy_out_2
    state_topic: "b2500/2/power/energy"
    power_id: b2500_total_power_out_2
    unit_of_measurement: kWh
    method: left
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    on_value:
      then:
        - script.execute: b2500_update_total_daily_energy_out
  - platform: template
    name: "Total Power In"
    id: b2500_total_in_power
    state_topic: "b2500/S/pv/power"
    retain: false
    accuracy_decimals: 0
    unit_of_measurement: W
    device_class: power

  - platform: template
    name: "Total Power Out"
    id: b2500_total_out_power
    state_topic: "b2500/S/power/power"
    retain: false
    accuracy_decimals: 0
    unit_of_measurement: W
    device_class: power

  - platform: template
    name: "Total Daily Energy In"
    id: b2500_total_daily_energy_in
    state_topic: "b2500/S/pv/energy"
    retain: false
    accuracy_decimals: 3
    unit_of_measurement: kWh
    device_class: energy

  - platform: template
    name: "Total Daily Energy Out"
    id: b2500_total_daily_energy_out
    state_topic: "b2500/S/power/energy"
    retain: false
    accuracy_decimals: 3
    unit_of_measurement: kWh
    device_class: energy

  - platform: template
    name: "Total Remaining Capacity"
    id: b2500_total_remaining_capacity
    state_topic: "b2500/S/battery/remaining_capacity"
    unit_of_measurement: Wh
    device_class: energy

script:
  - id: b2500_update_total_power_in
    then:
      - sensor.template.publish:
          id: b2500_total_in_power
          state: !lambda |-
            return id(b2500_total_power_in_1).state + id(b2500_total_power_in_2).state;
  - id: b2500_update_total_power_out
    then:
      - sensor.template.publish:
          id: b2500_total_out_power
          state: !lambda |-
            return id(b2500_total_power_out_1).state + id(b2500_total_power_out_2).state;
  - id: b2500_update_total_daily_energy_in
    then:
      - sensor.template.publish:
          id: b2500_total_daily_energy_in
          state: !lambda |-
            return id(b2500_total_daily_energy_in_1).state + id(b2500_total_daily_energy_in_2).state;
  - id: b2500_update_total_daily_energy_out
    then:
      - sensor.template.publish:
          id: b2500_total_daily_energy_out
          state: !lambda |-
            return id(b2500_total_daily_energy_out_1).state + id(b2500_total_daily_energy_out_2).state;
  - id: b2500_update_total_remaining_capacity
    then:
      - sensor.template.publish:
          id: b2500_total_remaining_capacity
          state: !lambda |-
            return id(b2500_battery_remaining_capacity_1).state + id(b2500_battery_remaining_capacity_2).state;
```
