### ISSUE TITLE
Missing Topics from Timer Settings

### ISSUE THREAD

**Issue by Dropsmasta** [tomquist/esphome-b2500#98]
Hi tomquist,
mir ist aufgefallen, das die Topics für die Start und End Time bei mir nicht vorhanden sind.

Mein Speicher:
![Image](https://github.com/user-attachments/assets/185e60d6-7cad-4d3f-963c-13212bef2691)
![Image](https://github.com/user-attachments/assets/574936aa-18d5-4539-bb3c-0a07cd24ca89)

In der Config.YAML sind sie alle aufgeführt (siehe Code ganz unten), aber in HomeAssistant sind nur die switch und number Entitäten der Timer Settings zu finden:

![Image](https://github.com/user-attachments/assets/67a10c65-ad22-4973-ac39-66e5b9740bd2)

Mich hatte es gewundert, dass mein ESP32-WROOM32 ständig Warnings ausgibt - hatte aber eigentlich vermutet, dass es am unzureichenden RAM liegt und mir deswegen bereits ein ESP32-S3 bestellt.

> [22:07:15][W][component:170]: Component mqtt cleared Warning flag
> [22:07:29][W][b2500:305]: Unknown command
> [22:07:29][W][b2500:235]: Failed to receive packet
> [22:07:30][W][b2500:305]: Unknown command
> [22:07:30][W][b2500:235]: Failed to receive packet
> [22:07:30][W][component:237]: Component esp32_ble took a long time for an operation (58 ms).
> [22:07:30][W][component:238]: Components should block for at most 30 ms.

Dann bin ich darauf gestoßen das die oben genannten Topics nicht vorhanden sind, vielleicht ist das Grund warum hier ständig
> Unknown command
> Failed to receive packet

in den Logs ausgegeben wird?

Grüße!

```
datetime:
  - platform: b2500
    b2500_id: b2500_1
    generation: 2
    timer1_start:
      id: b2500_timer1_time_start_1
      name: "B1: Timer 1 Start Time"
      state_topic: "b2500/1/timer/1/start"
      command_topic: "b2500/1/timer/1/start/set"
    timer1_end:
      id: b2500_timer1_time_end_1
      name: "B1: Timer 1 End Time"
      state_topic: "b2500/1/timer/1/end"
      command_topic: "b2500/1/timer/1/end/set"
    timer2_start:
      id: b2500_timer2_time_start_1
      name: "B1: Timer 2 Start Time"
      state_topic: "b2500/1/timer/2/start"
      command_topic: "b2500/1/timer/2/start/set"
    timer2_end:
      id: b2500_timer2_time_end_1
      name: "B1: Timer 2 End Time"
      state_topic: "b2500/1/timer/2/end"
      command_topic: "b2500/1/timer/2/end/set"
    timer3_start:
      id: b2500_timer3_time_start_1
      name: "B1: Timer 3 Start Time"
      state_topic: "b2500/1/timer/3/start"
      command_topic: "b2500/1/timer/3/start/set"
    timer3_end:
      id: b2500_timer3_time_end_1
      name: "B1: Timer 3 End Time"
      state_topic: "b2500/1/timer/3/end"
      command_topic: "b2500/1/timer/3/end/set"
    timer4_start:
      id: b2500_timer4_time_start_1
      name: "B1: Timer 4 Start Time"
      state_topic: "b2500/1/timer/4/start"
      command_topic: "b2500/1/timer/4/start/set"
    timer4_end:
      id: b2500_timer4_time_end_1
      name: "B1: Timer 4 End Time"
      state_topic: "b2500/1/timer/4/end"
      command_topic: "b2500/1/timer/4/end/set"
    timer5_start:
      id: b2500_timer5_time_start_1
      name: "B1: Timer 5 Start Time"
      state_topic: "b2500/1/timer/5/start"
      command_topic: "b2500/1/timer/5/start/set"
    timer5_end:
      id: b2500_timer5_time_end_1
      name: "B1: Timer 5 End Time"
      state_topic: "b2500/1/timer/5/end"
      command_topic: "b2500/1/timer/5/end/set"
```
